---
name: Bug Report
about: Create a report to help us improve
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: ''
---

## Bug Description

A clear and concise description of what the bug is.

## Steps to Reproduce

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected Behavior

A clear and concise description of what you expected to happen.

## Actual Behavior

A clear and concise description of what actually happened.

## Screenshots

If applicable, add screenshots to help explain your problem.

## Environment

**Application:**
- [ ] Web Application
- [ ] Mobile Application  
- [ ] API
- [ ] Desktop Application

**Browser (if web-related):**
- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Mobile (if mobile-related):**
- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- App Version: [e.g. 1.0.0]

**System:**
- OS: [e.g. Windows 10, macOS, Ubuntu]
- Node Version: [e.g. 20.x]
- Package Manager: [e.g. pnpm 8.x]

## Additional Context

Add any other context about the problem here.

## Logs

```
Please paste any relevant logs here
```

## Checklist

- [ ] I have searched existing issues to ensure this is not a duplicate
- [ ] I have provided all requested information
- [ ] I have tested this on the latest version
- [ ] I have included steps to reproduce the issue