name: auto-fix-disabled

# Minimal disabled workflow used for local `act` runs.
on: [workflow_dispatch]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo "auto-fix workflow disabled for local testing"

# Intentionally disabled for local act runs. Restore original workflow
# in the remote repo to enable GitHub Actions.
