name: CI - Pull Request

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    pr-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm -w lint

            - name: Typecheck
              run: pnpm -w type-check

            - name: Run critical tests
              run: pnpm test:critical

            - name: Build web (production, keep source-maps per next.config)
              run: pnpm --filter @udp/web build

            - name: Run duplicate-Yjs detector
              run: |
                  mkdir -p artifacts/duplicate-yjs
                  pnpm check:duplicate-yjs -- --dir apps/web/.next --report artifacts/duplicate-yjs/pr-report.json

            - name: Upload duplicate-Yjs report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: duplicate-yjs-report
                  path: artifacts/duplicate-yjs/pr-report.json

            - name: read_report
              id: read_report
              if: always()
              env:
                REPORT_PATH: artifacts/duplicate-yjs/pr-report.json
              run: |
                if [ -f "$REPORT_PATH" ]; then
                  node -e "const r=JSON.parse(require('fs').readFileSync('$REPORT_PATH','utf8')); const s=\`scanned:${r.scannedFiles} flagged:${r.flaggedFiles} severity:${r.severity} strict:${r.strict}\`; console.log(s);" > report_summary.txt
                  echo "summary<<EOF" >> $GITHUB_OUTPUT
                  cat report_summary.txt >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT
                else
                  echo "summary<<EOF" >> $GITHUB_OUTPUT
                  echo "no report generated" >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT
                fi

            - name: Post duplicate-Yjs summary as PR comment
              if: always()
              uses: peter-evans/create-or-update-comment@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                issue-number: ${{ github.event.pull_request.number }}
                body: |
                  **duplicate-Yjs detector report**
                  
                  ${{ steps.read_report.outputs.summary }}
