name: CI

on:
  pull_request:
    branches: [main, feat/*]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Enable Corepack & pnpm (early)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Enable Corepack & pnpm (early)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: Enable Corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Debug pnpm availability
        run: |
          echo "--- env ---"
          env | sort
          echo "--- versions ---"
          node --version
          npm --version
          corepack --version 2>/dev/null || echo 'corepack not found'
          pnpm --version 2>/dev/null || echo 'pnpm not found'
          which pnpm || true
          echo "--- PATH ---"
          echo "$PATH"


      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate environment (main only)
        if: github.ref == 'refs/heads/main'
        run: pnpm ci:validate-env

      - name: Check Prettier formatting
        run: pnpm format:check

      - name: Run ESLint
        run: pnpm lint

      - name: Run TypeScript type check
        run: pnpm type-check

      - name: Run tests
        run: pnpm test

      - name: Build web
        run: pnpm --filter @udp/web build
