name: CI

on:
  pull_request:
    branches: [main, feat/*]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "18"

      - name: Enable Corepack and install pnpm (pinned)
        run: |
          corepack enable
          # Pin to the repo's packageManager / pnpm version to ensure reproducible CI
          corepack prepare pnpm@9.0.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate environment (main only)
        if: github.ref == 'refs/heads/main'
        run: pnpm ci:validate-env

      - name: Check Prettier formatting
        run: pnpm format:check

      - name: Run ESLint
        run: pnpm lint

      - name: Run TypeScript type check
        run: pnpm type-check

      - name: Run tests
        run: pnpm test:ci

      - name: Build web
        run: pnpm --filter @udp/web build
