name: CI

on:
  pull_request:
    branches: [main, feat/*]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack & pnpm (early)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Setup pnpm (after setup-node)
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Enable Corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate environment (main only)
        if: github.ref == 'refs/heads/main'
        run: pnpm ci:validate-env

      - name: Check Prettier formatting
        run: pnpm format:check

      - name: Run ESLint
        run: pnpm lint

      - name: Run TypeScript type check
        run: pnpm type-check

      - name: Run tests
        run: pnpm test:ci

      - name: Build web
        run: pnpm --filter @udp/web build
