name: PR checks (lint & type-check)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-type-check:
    name: Lint & Type-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Run type-check
        run: pnpm type-check

      - name: Run console-check (dry-run)
        run: pnpm -w run check:console

      - name: Upload console-check report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: console-replace-report
          path: artifacts/console-replace-report.json
