name: PR checks (lint & type-check)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-type-check:
    name: Lint & Type-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      # Solution: ensure pnpm is available in the runner before any pnpm commands
      # You can use Corepack (recommended) or install pnpm globally.
      # The step below installs pnpm globally to guarantee availability.
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm lint

      - name: Run type-check
        run: pnpm type-check
