name: PR checks (lint & type-check)
name: PR checks (lint & type-check)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-type-check:
    name: Lint & Type-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.0

      # Ensure pnpm is available and pinned to the repo's packageManager version
      - name: Enable Corepack and prepare pnpm (pinned)
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Diagnostic: Prisma versions & resolved paths
        run: node .github/scripts/prisma-diagnostic.js

      - name: Run lint
        run: pnpm lint

      - name: Run type-check
        run: pnpm type-check
name: PR checks (lint & type-check)
