name: PR checks (lint & type-check)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-type-check:
    name: Lint & Type-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Ensure pnpm is available and pinned to the repo's packageManager version
      - name: Enable Corepack and prepare pnpm (pinned)
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Diagnostic: Prisma versions & resolved paths
        if: always()
        run: |
          node -e 'const fs=require("fs"), path=require("path");
          try{ console.log("prisma:", require("prisma/package.json").version) }catch(e){ console.log("prisma: not found -", e.message) }
          try{ console.log("@prisma/client:", require("@prisma/client/package.json").version) }catch(e){ console.log("@prisma/client: not found -", e.message) }
          try{ const p=require.resolve("@prisma/client"); console.log("@prisma/client resolved:", p); const dir=path.dirname(p); console.log("dir listing:\n"+fs.readdirSync(dir).join("\n")) }catch(e){ console.log("resolve failed:", e.message) }'

      - name: Run lint
        run: pnpm lint

      - name: Run type-check
        run: pnpm type-check
